In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("maltegrosse/8-m-spotify-tracks-genre-audio-features")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/maltegrosse/8-m-spotify-tracks-genre-audio-features?dataset_version_number=1...

100%|██████████| 1.87G/1.87G [03:26<00:00, 9.70MB/s]

Extracting files...

Path to dataset files: /Users/akovel/.cache/kagglehub/datasets/maltegrosse/8-m-spotify-tracks-genre-audio-features/versions/1

In [4]:
import pandas as pd
import sqlite3

In [17]:
db_path = path + "/spotify.sqlite"

In [25]:
con = sqlite3.connect(db_path)
con.text_factory = lambda x: x.decode(encoding='utf-8',errors = 'ignore')
cur = con.cursor()

cur.execute("SELECT name FROM sqlite_master  WHERE type='table';")
print(cur.fetchall())

[('albums',), ('artists',), ('audio_features',), ('genres',), ('r_albums_artists',), ('r_albums_tracks',), ('r_artist_genre',), ('r_track_artist',), ('tracks',)]

In [27]:
albums = pd.read_sql_query("SELECT * from albums", con)
albums.head()

,id,name,album_group,album_type,release_date,popularity
0,2jKoVlU7VAmExKJ1Jh3w9P,"Alkaholik (feat. Erik Sermon, J Ro & Tash)",,album,954633600000,0
1,4JYUDRtPZuVNi7FAnbHyux,"Flava in Ya Ear Remix (feat. Notorious B.I.G.,...",,single,757382400000,0
2,6YjKAkDYmlasMqYw73iB0w,Bitch Please II,,album,959040000000,0
3,2YlvHjDb4Tyxl4A1IcDhAe,Just Dippin',,compilation,1104537600000,0
4,3UOuBNEin5peSRqdzvlnWM,Still D.R.E.,,album,942710400000,0

In [28]:
artists = pd.read_sql_query("SELECT * from artists", con)
artists.head()

           name                      id  popularity  followers
0        Xzibit  4tujQJicOnuZRLiBFdp3Ou          69    1193665
1  Erick Sermon  2VX0o9LDIVmKIgpnwdJpOJ          54     142007
2         J. Ro  3iBOsmwGzRKyR0vs2I61xP          45        158
3          Tash  22qf8cJRzBjIWb2Jc4JeOr          48       3421
4    Craig Mack  4akj4uteQQrrGxhX9Rjuyf          55     161966

In [29]:
audio_features = pd.read_sql_query("SELECT * from audio_features", con)
audio_features.head()

,id,acousticness,analysis_url,danceability,duration,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,2jKoVlU7VAmExKJ1Jh3w9P,0.1800,https://api.spotify.com/v1/audio-analysis/2jKo...,0.893,219160,0.514,0.000000,11,0.0596,-5.080,1,0.283,95.848000,4,0.787
1,4JYUDRtPZuVNi7FAnbHyux,0.2720,https://api.spotify.com/v1/audio-analysis/4JYU...,0.520,302013,0.847,0.000000,9,0.3250,-5.300,1,0.427,177.371002,4,0.799
2,6YjKAkDYmlasMqYw73iB0w,0.0783,https://api.spotify.com/v1/audio-analysis/6YjK...,0.918,288200,0.586,0.000000,1,0.1450,-2.890,1,0.133,95.516998,4,0.779
3,2YlvHjDb4Tyxl4A1IcDhAe,0.5840,https://api.spotify.com/v1/audio-analysis/2Ylv...,0.877,243013,0.681,0.000000,1,0.1190,-6.277,0,0.259,94.834999,4,0.839
4,3UOuBNEin5peSRqdzvlnWM,0.1700,https://api.spotify.com/v1/audio-analysis/3UOu...,0.814,270667,0.781,0.000518,11,0.0520,-3.330,1,0.233,93.445000,4,0.536

In [31]:
tracks = pd.read_sql_query("SELECT * from tracks", con)
tracks.head()

,id,disc_number,duration,explicit,audio_feature_id,name,preview_url,track_number,popularity,is_playable
0,1dizvxctg9dHEyaYTFufVi,1,275893,1,1dizvxctg9dHEyaYTFufVi,Gz And Hustlas (feat. Nancy Fletcher),,12,0,NaN
1,2g8HN35AnVGIk7B8yMucww,1,252746,1,2g8HN35AnVGIk7B8yMucww,Big Poppa - 2005 Remaster,https://p.scdn.co/mp3-preview/770e023eb0318270...,13,77,NaN
2,49pnyECzcMGCKAqxfTB4JZ,3,315080,0,49pnyECzcMGCKAqxfTB4JZ,"You Were Born - Early Version Of ""One Of The T...",,6,8,1.0
3,4E5IFAXCob6QqZaJMTw5YN,1,240800,1,4E5IFAXCob6QqZaJMTw5YN,Poppin' Them Thangs,https://p.scdn.co/mp3-preview/f3b556ced9657f89...,2,70,NaN
4,1gSt2UlC7mtRtJIc5zqKWn,2,203666,0,1gSt2UlC7mtRtJIc5zqKWn,"It's Hard To Say ""I Do"", When I Don't",,2,50,NaN

In [30]:
r_albums_artists = pd.read_sql_query("SELECT * from r_albums_artists", con)
r_albums_artists.head()

                 album_id               artist_id
0  6os2Mv58OYnQClPf7B9E1s  2HS2wQTJXpA65XWOKlAVxk
1  5XXN1tFQg7D7U1NSVh5fjf  3VBpsrUi2vV7Uj87ONHu7Z
2  63wFVCPZxdaFL9WKXbIQ5m  1kC8lmaSblf7GyK915496r
3  0z7p1tHVJ6s5wxAdj9iJ6e  2bTFaANevDESpT5eGWsZ7a
4  4afYJvrsp90d3V2COlLHVE  2maQMqxNnlRrBrS1oAsrX9

Но остальное это уже отношения